
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # password arbitraire que j'ai ajoutee moi meme
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qJ8mR4kL9pN2xV7bF3tY6wE5rA1sD4gH=}

      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    ports:
      - "50589:80"
    environment:
      # Uncomment the following line to disable HTTPS,
      MERCURE_PUBLISHER_JWT_KEY: 'a94f4b2d1c5e43719dede91f8a21f3b7e61720d5bcdafc5e783c7f6f4a15a2ef!'
      MERCURE_SUBSCRIBER_JWT_KEY: 'a94f4b2d1c5e43719dede91f8a21f3b7e61720d5bcdafc5e783c7f6f4a15a2ef!'
      ALLOW_ANONYMOUS: 1
      CORS_ALLOWED_ORIGINS: '*'
      PUBLISH_ALLOWED_ORIGINS: '*'
      SERVER_NAME: ':80'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        log
        debug
        http_port 80
        auto_https off
      
    # la partie suivante est a ajouter pour le healthcheck de mercure
    # pour avoir les log durant le developpement
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
  database_data:
###< doctrine/doctrine-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###