monolog:
    channels:
        - papertrail
    
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
        
        papertrail:
            type: syslog
            ident: 'openhub'
            facility: user
            level: info
            # Solution: fournir des valeurs par d√©faut
            host: '%env(default::PAPERTRAIL_HOST)%'
            port: '%env(default::PAPERTRAIL_PORT)%'
            channel: papertrail