monolog:
    channels:
        - papertrail
    
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
        
        papertrail:
            type: buffer
            handler: papertrail_http
            level: info
            channels: [papertrail]
        
        papertrail_http:
            type: curl
            url: '%env(PAPERTRAIL_URL)%'
            level: info
            headers:
                Content-Type: "application/json"
                Authorization: "Bearer %env(PAPERTRAIL_TOKEN)%"
            formatter: monolog.formatter.json
            # Pas de méthode, curl utilise POST par défaut avec des données