monolog:
    channels:
        - papertrail
    
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
        
        papertrail:
            type: whatfailuregroup
            members: [papertrail_http]
        
        papertrail_http:
            type: buffer
            handler: papertrail_http_buffer
        
        papertrail_http_buffer:
            type: curl
            level: info
            channel: papertrail
            url: '%env(PAPERTRAIL_URL)%'
            method: POST
            headers:
                Content-Type: application/json
                Authorization: 'Bearer %env(PAPERTRAIL_TOKEN)%'
            formatter: monolog.formatter.json