monolog:
    channels:
        - papertrail
    
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
        
        papertrail:
            type: syslog
            ident: 'openhub'
            facility: user
            level: info
            host: '%env(PAPERTRAIL_HOST)%'
            port: '%env(int:PAPERTRAIL_PORT)%'
            channel: papertrail