global:
  scrape_interval: 30s

remote_write:
  - url: https://prometheus-prod-67-prod-us-west-0.grafana.net/api/prom/push
    basic_auth:
      username: 2933575
      password: ${GRAFANA_TOKEN}

scrape_configs:
  - job_name: openhub_frontend
    static_configs:
      - targets: ["openhub-backend.onrender.com"]
    scheme: https
    metrics_path: /metrics/frontend

  - job_name: openhub_backend
    static_configs:
      - targets: ["openhub-backend.onrender.com"]
    scheme: https
    metrics_path: /metrics/backend
    scrape_interval: 30s